### ISSUE TITLE
lambda increment functions choke on ratelimited views

### ISSUE THREAD

**Issue by jvc26** [gmcquillan/django-brake#10]
Currently:

    @ratelimit(increment=lambda req, resp: resp.count)
    def login(request):
        resp = HttpResponseRedirect()
        if login_is_correct:
            # Do not count correct logins against the limit.
            resp.count = False
        else:
            resp.count = True
        return resp

Fails if the ratelimit kicks in:

    AttributeError: 'HttpResponseTooManyRequests' object has no attribute 'count'

Ratelimit decorator should not increment, or should not call increment function if the response is a ```HttpResponseTooManyRequests``` object

**Comment by skorokithakis** [comment]
Should this be closed?
