### ISSUE TITLE
Wrong limits applied with `increment`.

### ISSUE THREAD

**Issue by skorokithakis** [gmcquillan/django-brake#19]
The cache key only includes the period, so if you have two rate-limits, one permissive for valid requests and one less permissive for invalid requests, the permissive ones count against the non-permissive ones:

```
@method_decorator(ratelimit(block=True, rate="200/m"))
@method_decorator(ratelimit(block=True, rate="2/m", increment=lambda x, response: response == 403))
```

This should allow 200 valid requests per minute and 2 invalid requests, but it only allows 2 requests, valid or invalid. I suggest the rate also be included in the cache key name.

**Comment by gmcquillan** [comment]
Interesting. Yeah. that sounds like a good idea to me.

**Comment by skorokithakis** [comment]
I had a look and the problem is that `count` isn't passed in `_keys` for the backend by default. Can we pass it without breaking backwards compatibility?

**Comment by gmcquillan** [comment]
I'll check it out.

**Comment by gmcquillan** [comment]
So, for your first use-case, if you don't have more than a couple of each category, you could just set ``use_request_path=True`` for the cases where you want to ratelimit valid requests. It'll make sure that you don't collide with any of the buckets which are per-function (which is the default):

https://github.com/gmcquillan/django-brake/blob/master/brake/decorators.py#L62

**Comment by skorokithakis** [comment]
Hmm, how does that help? It's the same path and view function for both.

My workaround consisted of giving them unique durations, like "2/61s", "200/62s", but that's suboptimal.

**Comment by gmcquillan** [comment]
Right, but if you're not setting use_request_path to True, then none of that information is in the key. It defaults to whatever the function name is. Checkout the link I sent. The request_path takes the place of the function name, so they'd have different buckets if you switched this (even on the same function).

**Comment by skorokithakis** [comment]
Ah, I must be missing something. I have a single view with two limits, the path for both limits is "/info/", since there's a single view URL. How would the request path help there?

**Comment by gmcquillan** [comment]
Try this:

```python
@method_decorator(
ratelimit(use_request_path=True, block=True, rate="200/m"))
@method_decorator(
ratelimit(block=True, rate="2/m", increment=lambda x, response: response == 403))
```

For IP-based buckets, the keys for these should look something like:
```
':1:rl:func:/info/:period:60:ip:127.0.0.1'
':1:rl:func:your_function_name:period:60:ip:127.0.0.1'
```

**Comment by skorokithakis** [comment]
Oh, you meant one of each, I see. I thought you meant changing to the request path for all the limits. This would work as well, thanks. I'll think about how it can be solved, rather than worked around, but putting the entire limit in the key (rather than just the period) would be a good solution. Essentially, you want each limit key to be as unique as possible, and the limit string is the best description of that.

**Comment by gmcquillan** [comment]
Is this still a problem?

**Comment by skorokithakis** [comment]
Yes, I worked around it by writing limits like "10/61s", "200/62s", etc.
