### ISSUE TITLE
Does django-brake support Class-Based Views?

### ISSUE THREAD

**Issue by mhb11** [gmcquillan/django-brake#28]
Couldn't find it in the documentation.

**Comment by gmcquillan** [comment]
There's not explicit support, but I'd wager that you could do it by overriding the `as_view` function, and putting the ratelimit decorator on it.

Something like this might work?

```python
from brake.decorators import ratelimit
from django.views.generic import TemplateView

class MyView(TemplateView):

     @ratelimit
    def as_view(*args, **kwargs):
        return super(MyView).as_view(*args, **kwargs)
```

**Comment by mhb11** [comment]
Makes sense. I'm going to give it a shot.

**Comment by gmcquillan** [comment]
Better yet, the dispatch classmethod might be a better one to wrap.

**Comment by dqd** [comment]
Just a note for somebody who would be interested to see the solution. You need to use the `method_decorator`, as noted in https://docs.djangoproject.com/en/dev/topics/class-based-views/intro/#decorating-the-class. For example:

```python
from brake.decorators import ratelimit
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator

class MyView(TemplateView):
    @method_decorator(ratelimit(rate='10/m', method='POST'))
    def dispatch(self, *args, **kwargs):
        return super(TemplateView, self).dispatch(*args, **kwargs)
```
