### ISSUE TITLE
Elegant way to override PERIODS

### ISSUE THREAD

**Issue by mhb11** [gmcquillan/django-brake#29]
What do you suggest is the most elegant way to customize PERIODS? For instance, instead of /s, /m, /h or /d intervals, what if one wanted intervals such as 5 seconds, 15 seconds, 30 seconds, 45 seconds, etc? `@ratelimit(rate='1/5s')` for instance.

**Comment by gmcquillan** [comment]
Have you tried '.2s'?

**Comment by mhb11** [comment]
I'll try

**Comment by mhb11** [comment]
So the final word is, config such as `@ratelimit(rate='3/10s') `works perfectly.
