### ISSUE TITLE
Some keys are added without expiration.

### ISSUE THREAD

**Issue by skorokithakis** [gmcquillan/django-brake#30]
I'm seeing keys added without expiration. Things like:

```
:1:rl:func:bound_func:period:61:ip:123.123.123.123
```

Where the expiration should be less than 61 seconds, but is actually `-1`. I don't see how this can be happening, as django's caching backend only considers `None` to be "don't expire". Any ideas?

**Comment by gmcquillan** [comment]
I'll take a look; I wonder if there's any logic for times which are less than 60 seconds to be short circuited to None somewhere in the cache decorators.

**Comment by skorokithakis** [comment]
Sorry, that's the pull request that was just merged, no need to take a look, thanks!

**Comment by gmcquillan** [comment]
released: https://pypi.python.org/pypi/django-brake/1.5.2

**Comment by skorokithakis** [comment]
Thank you!
