### ISSUE TITLE
Small ratelimit when using utils.get_limit

### ISSUE THREAD

**Issue by larchchen** [gmcquillan/django-brake#33]
Hi,

   I found out that if I want use utils.get_limits to set small ratelimit e.g. 1/m, 2/5m, etc. It would not work because at line 16 `count += 10` it assume the limits will increase exactly 10 per period.

Thanks,
Lin

**Comment by gmcquillan** [comment]
Thanks, I'll check this out.

**Comment by gmcquillan** [comment]
Fixed in #34
