### ISSUE TITLE
Rate-limiting based on request.user.id

### ISSUE THREAD

**Issue by mhb11** [gmcquillan/django-brake#37]
I'm a little hazy about tying something like `request.user.id` into the `@ratelimit` decorator. E.g., how would `request.user.id` be made available to the decorator? Could you provide a quick example? 

Most of my users use mobile internet, so for me, more effective than ip-based rate limiting is user_id based rate limiting. Would love to get an illustrative example of how to implement it.

**Comment by gmcquillan** [comment]
The decorator pretty much assumes you're dealing with form fields. It wouldn't be hard to add another method of rate limiting, which accepts a callable to determine the label of the value you're trying to ratelimit.

**Comment by mhb11** [comment]
Okay. What I had in mind was `@ratelimit(field='user_id',ip=False,rate='1/2s')` and then passing the user pk in the `<form>` like so: `<input type="hidden" name="user_id" value="{{ user.id }}">`. That should do it right?

**Comment by gmcquillan** [comment]
Looks like it. Test it out!
