### ISSUE TITLE
cache key prefix problem

### ISSUE THREAD

**Issue by wingyiu** [gmcquillan/django-brake#6]
i check the memcached, found somthing:

`ITEM YC:1::1:rl:func:login_failure:period:86400:ip:127.0.0.1 [2 b; 1383303483 s]`

the code

    BASE_CACHE.make_key(CACHE_PREFIX + k) for k in keys

generate the `:1:rl:func:login_failure:period:86400:ip:127.0.0.1`, and then 

    cache.set_many(counters, timeout=period)

append the `YC:1:`

i think `BASE_CACHE` should change to `cache`

**Comment by gmcquillan** [comment]
@wingyiu Ah, I finally reproduced the error. It looks systematic, but as long as it's always happening it's not the wors

**Comment by gmcquillan** [comment]
Fixed in #24.
